### ISSUE TITLE
Derivatives: task list

### ISSUE THREAD

**Issue by JCGoran** [JCGoran/fitk#9]
The below are all leftover tasks from #5 that were not mandatory for that PR to get merged.

* [x] implement third order mixed derivatives and test them
* [ ] (nice to have) figure out how to return coordinate metadata (maybe `signal` should return the tuple `(coords, values)`? Or a separate (data) class with properties `coords` and `values`). Note that the coordinates are not needed anywhere in the code, they would just be there as a convenience for the user, in case they want to construct the derivatives themselves, or if they want to easily plot the derivatives without re-computing the coordinates.
* [ ] (nice to have) implement adaptive step size so the user doesn't have to guess whether the derivative computed has actually converged (and hasn't experienced underflow)
* [ ] implement interfaces to various third-party software:
     * [x] #44
     * [x] [CAMB](https://github.com/cmbant/CAMB)
     * [ ] [PyCosmo](https://cosmo-docs.phys.ethz.ch/PyCosmo/)
* [ ] (nice to have) make a metaclass that can be used to streamline the creation of interfaces to third-party software
* [ ] (nice to have) given an interface to some third-party software, make it possible to specify _which_ parameters we can be varied, so the user does not have to guess ("do I use `omega_m`? `Omega_m`? `Omega_matter`?")
* [ ] (nice to have) implement computation of derivatives using the complex step approximation
* [ ] #42
